### PR TITLE
Allow sidebar to set the views of a scaffold

### PR DESCRIPTION
**Pull request by Tehsurfer**
This can be tested on the colon scaffold:
image

### CODE REVIEW

**Comment by alan-wu** [comment]
@Tehsurfer I have added semi-colons to keep things consistent and also create a patch up version of the sidebar to fix simulationvuer event and hide the "Samples on scaffold" text when sample size is 0.

Future improvements include:
Look into the sizing issue on the contextual information, it expands the width when it is opened.
The information should not be shown on unrelated context.

**Review by alan-wu — APPROVED** [review]
See comment for future improvements.

**Comment by Tehsurfer** [comment]
@alan-wu thank you! 

> semi-colons to keep things consistent
Sorry about that! missed this

> "Samples on scaffold" text when sample size is 0.
Oh yeah sorry I did patch this but maybe it had not updated the sidebar version here

**Comment by Tehsurfer** [comment]
> Look into the sizing issue on the contextual information, it expands the width when it is opened.
I didn't notice this, will fix 

> The information should not be shown on unrelated context.
Will fix this asap

**Review by alan-wu — APPROVED** [review]

**Pull request merged**
